# Pandas Basics

In [2]:
import pandas as pd
import numpy as np
df=pd.DataFrame({'A':[1,2,3],'B':[4,5,6]})
df

   A  B
0  1  4
1  2  5
2  3  6

In [17]:
s=pd.Series([1,2,3,'A',np.nan], index=['x','y','z','a','b'])
s
students_name=['Dhyan','Raj','Krush','Sujal','Rudra']
marks=[100,90,80,70,60]
s=pd.Series(marks,index=students_name,name='Students_Marks')
s

Dhyan    100
Raj       90
Krush     80
Sujal     70
Rudra     60
Name: Students_Marks, dtype: int64

In [31]:
df=pd.read_csv('bollywood.csv')
df.shape
df

                                     movie              lead
0                 Uri: The Surgical Strike     Vicky Kaushal
1                            Battalion 609       Vicky Ahuja
2     The Accidental Prime Minister (film)       Anupam Kher
3                          Why Cheat India     Emraan Hashmi
4                          Evening Shadows  Mona Ambegaonkar
...                                    ...               ...
1495                Hum Tumhare Hain Sanam    Shah Rukh Khan
1496                   Aankhen (2002 film)  Amitabh Bachchan
1497                       Saathiya (film)      Vivek Oberoi
1498                        Company (film)        Ajay Devgn
1499                  Awara Paagal Deewana      Akshay Kumar

[1500 rows x 2 columns]

In [10]:
df.describe

<bound method NDFrame.describe of                                      movie              lead
0                 Uri: The Surgical Strike     Vicky Kaushal
1                            Battalion 609       Vicky Ahuja
2     The Accidental Prime Minister (film)       Anupam Kher
3                          Why Cheat India     Emraan Hashmi
4                          Evening Shadows  Mona Ambegaonkar
...                                    ...               ...
1495                Hum Tumhare Hain Sanam    Shah Rukh Khan
1496                   Aankhen (2002 film)  Amitabh Bachchan
1497                       Saathiya (film)      Vivek Oberoi
1498                        Company (film)        Ajay Devgn
1499                  Awara Paagal Deewana      Akshay Kumar

[1500 rows x 2 columns]>

In [11]:
df.head

<bound method NDFrame.head of                                      movie              lead
0                 Uri: The Surgical Strike     Vicky Kaushal
1                            Battalion 609       Vicky Ahuja
2     The Accidental Prime Minister (film)       Anupam Kher
3                          Why Cheat India     Emraan Hashmi
4                          Evening Shadows  Mona Ambegaonkar
...                                    ...               ...
1495                Hum Tumhare Hain Sanam    Shah Rukh Khan
1496                   Aankhen (2002 film)  Amitabh Bachchan
1497                       Saathiya (film)      Vivek Oberoi
1498                        Company (film)        Ajay Devgn
1499                  Awara Paagal Deewana      Akshay Kumar

[1500 rows x 2 columns]>

In [24]:
df2=pd.read_csv('subs.csv')
df2.head()

   Subscribers gained
0                  48
1                  57
2                  40
3                  43
4                  44

In [27]:
df2.sum()

Subscribers gained    49510
dtype: int64

In [28]:
df2.min()

Subscribers gained    33
dtype: int64

In [29]:
df2.max()

Subscribers gained    396
dtype: int64

In [30]:
df=df.squeeze()
df

                                     movie              lead
0                 Uri: The Surgical Strike     Vicky Kaushal
1                            Battalion 609       Vicky Ahuja
2     The Accidental Prime Minister (film)       Anupam Kher
3                          Why Cheat India     Emraan Hashmi
4                          Evening Shadows  Mona Ambegaonkar
...                                    ...               ...
1495                Hum Tumhare Hain Sanam    Shah Rukh Khan
1496                   Aankhen (2002 film)  Amitabh Bachchan
1497                       Saathiya (film)      Vivek Oberoi
1498                        Company (film)        Ajay Devgn
1499                  Awara Paagal Deewana      Akshay Kumar

[1500 rows x 2 columns]

In [34]:
df[-5:]

                       movie              lead
1495  Hum Tumhare Hain Sanam    Shah Rukh Khan
1496     Aankhen (2002 film)  Amitabh Bachchan
1497         Saathiya (film)      Vivek Oberoi
1498          Company (film)        Ajay Devgn
1499    Awara Paagal Deewana      Akshay Kumar

In [35]:
df[::2]

                                     movie              lead
0                 Uri: The Surgical Strike     Vicky Kaushal
2     The Accidental Prime Minister (film)       Anupam Kher
4                          Evening Shadows  Mona Ambegaonkar
6                            Fraud Saiyaan      Arshad Warsi
8         Manikarnika: The Queen of Jhansi    Kangana Ranaut
...                                    ...               ...
1490                      Raaz (2002 film)        Dino Morea
1492            Waisa Bhi Hota Hai Part II      Arshad Warsi
1494                                Kaante  Amitabh Bachchan
1496                   Aankhen (2002 film)  Amitabh Bachchan
1498                        Company (film)        Ajay Devgn

[750 rows x 2 columns]

In [37]:
'Alia Bhatt' in df.values

True

In [49]:
counts = df['lead'].value_counts()

print(f'Actors with more than 20 movies: {counts[counts > 20]}')

Actors with more than 20 movies: lead
Akshay Kumar        48
Amitabh Bachchan    45
Ajay Devgn          38
Salman Khan         31
Sanjay Dutt         26
Shah Rukh Khan      22
Emraan Hashmi       21
Name: count, dtype: int64

In [50]:
df.value_counts()

movie                     lead
Tanu Weds Manu: Returns   Kangana Ranaut      2
Gabbar Is Back            Akshay Kumar        2
Andaaz                    Akshay Kumar        2
Uri: The Surgical Strike  Vicky Kaushal       1
Battalion 609             Vicky Ahuja         1
                                             ..
Hum Tumhare Hain Sanam    Shah Rukh Khan      1
Aankhen (2002 film)       Amitabh Bachchan    1
Saathiya (film)           Vivek Oberoi        1
Company (film)            Ajay Devgn          1
Awara Paagal Deewana      Akshay Kumar        1
Name: count, Length: 1497, dtype: int64

In [53]:
df.head()

                                  movie              lead
0              Uri: The Surgical Strike     Vicky Kaushal
1                         Battalion 609       Vicky Ahuja
2  The Accidental Prime Minister (film)       Anupam Kher
3                       Why Cheat India     Emraan Hashmi
4                       Evening Shadows  Mona Ambegaonkar

In [55]:
df[df['movie']=='Andaaz']

       movie          lead
1417  Andaaz  Akshay Kumar
1418  Andaaz  Akshay Kumar

In [59]:
df.iloc[[1417,1418]]

       movie          lead
1417  Andaaz  Akshay Kumar
1418  Andaaz  Akshay Kumar

In [60]:
df.isnull().sum()

movie    0
lead     0
dtype: int64

In [64]:
df[df['movie'].duplicated()]

                        movie            lead
358   Tanu Weds Manu: Returns  Kangana Ranaut
368            Gabbar Is Back    Akshay Kumar
1418                   Andaaz    Akshay Kumar

In [65]:
df.shape

(1500, 2)

In [68]:
df.drop_duplicates(inplace=True)

In [69]:
df.shape

(1497, 2)